version: 0.2

phases:
  install:
    commands:
      - npm i -g npm
      - npm i

  build:
    commands:
      - npm run test

reports:
  jest_reports:
    files:
      - "test-report.xml"
    file-format: JUNITXML
    base-directory: "test/test-reports"
